-- Batch 11: Ten Kingdoms, 902-979. Mostly kings (王); where a ruler claimed
-- the imperial title huangdi is flagged. Every row keeps the state''s own
-- supreme title per design rule 1.
-- Source: Xin Wudai shi 新五代史 (ctext.org).

INSERT INTO rulers (id, personal_name, personal_name_cn, temple_name, posthumous_name, year_start, year_end, dynasty_id, predecessor_id, source, note) VALUES
(155, 'Yang Wo', '杨渥', NULL, 'King of Wu 吴王 (Jing 景)', 905, 908, 27, NULL,
 'Xin Wudai shi 新五代史, annals juan 61 (ctext.org)', 'Son of Yang Xingmi (d. 905, never a ruler here — Tang vassal); killed by his own ministers Xu Wen and Zhang Hao'),
(156, 'Yang Longyan', '杨隆演', 'Gaozu 高祖', 'King of Wu 吴王 (Xuan 宣)', 908, 921, 27, 155, 'Xin Wudai shi 新五代史, annals juan 61-62 (ctext.org)', 'Teenage puppet of Xu Wen; took the title King of Wu under Later Liang suzerainty; power stayed with the Xu Wen clan'),
(157, 'Yang Pu', '杨溥', NULL, NULL, 921, 937, 27, 156,
 'Xin Wudai shi 新五代史, annals juan 62 (ctext.org)', 'Claimed the imperial title 927 — the only Yang Wu ruler who did. Abdicated to Li Bian 937, died in custody; posthumous imperial name unsettled in sources — to verify'),
(158, 'Li Bian', '李昪 (born Xu Zhigao 徐知诰)', 'Liezu 烈祖', 'Guangwen 光文肃武孝高皇帝', 937, 943, 28, 157,
 'Xin Wudai shi 新五代史, annals juan 62 (ctext.org)', 'Xu Wen''s adopted heir; claimed Tang descent and the name Li Bian to found Southern Tang — an invented genealogy, as he surely knew'),
(159, 'Li Jing', '李璟', 'Yuanzong 元宗', 'Mingdao Chongde 明道崇德文宣孝皇帝', 943, 961, 28, 158, 'Xin Wudai shi 新五代史, annals juan 62 (ctext.org)', 'Lost Fujian and Chu lands; called himself guozhu 国主 and dropped the imperial style to please Later Zhou 958'),
(160, 'Li Yu', '李煜', NULL, 'Houzhu 后主 (Marquis of Weiming 违命侯)', 961, 976, 28, 159,
 'Xin Wudai shi 新五代史, annals juan 62 (ctext.org)', 'The poet ("Spring water flows east" 恰似一江春水向东流); surrendered 975/976; died in Song custody 978, allegedly poisoned. Same romanisation as Tang Daizong 李豫 (id 127)'),
(161, 'Qian Liu', '钱镠', 'Taizu 太祖', 'King Wusu 武肃王', 907, 932, 29, NULL,
 'Xin Wudai shi 新五代史, annals juan 67 (ctext.org)', 'Never claimed the imperial title — Wuyue stayed a loyal vassal of whichever dynasty ruled the north; sea-wall builder of Hangzhou'),
(162, 'Qian Yuanguan', '钱元瓘', 'Shizu 世宗', 'King Wenmu 文穆王', 932, 941, 29, 161, 'Xin Wudai shi 新五代史, annals juan 67 (ctext.org)', 'Died amid a palace fire and siege'),
(163, 'Qian Zuo', '钱佐', NULL, 'King Zhongxian 忠献王', 941, 947, 29, 162, 'Xin Wudai shi 新五代史, annals juan 67 (ctext.org)', 'Died at 19'),
(164, 'Qian Zong', '钱倧', NULL, 'King Zhongxun 忠逊王', 947, 947, 29, 163, 'Xin Wudai shi 新五代史, annals juan 67 (ctext.org)', 'Deposed by the general Hu Jinsi within months'),
(165, 'Qian Chu', '钱俶', NULL, 'King Zhongyi 忠懿王', 947, 978, 29, 164, 'Xin Wudai shi 新五代史, annals juan 67 (ctext.org)', 'Last Ten Kingdoms ruler standing; surrendered Hangzhou to the Song 978. Same romanisation as Qian Zong above — 倧/俶, tone and stroke apart'),
(166, 'Wang Jian', '王建', 'Gaozu 高祖', 'Shenwu Shengwen 神武圣文孝德惠皇帝', 907, 918, 30, NULL,
 'Xin Wudai shi 新五代史, annals juan 63 (ctext.org)', 'Claimed the imperial title 907 after the Tang fell — Former Shu. Ex-bandit background; posthumous form to verify against the cited juan'),
(167, 'Wang Yan', '王衍', NULL, 'Houzhu 后主 (Marquis of Shunzheng 顺正侯)', 918, 925, 30, 166, 'Xin Wudai shi 新五代史, annals juan 63 (ctext.org)', 'Former Shu fell to Later Tang 925; the whole clan killed on the road'),
(168, 'Meng Zhixiang', '孟知祥', 'Gaozu 高祖', 'Wuxiao 文孝圣武? — to verify', 934, 934, 31, NULL,
 'Xin Wudai shi 新五代史, annals juan 64 (ctext.org)', 'Later Tang''s Sichuan governor; took the imperial title 934, died within the year. Posthumous form to verify against the cited juan'),
(169, 'Meng Chang', '孟昶', NULL, NULL, 934, 965, 31, 168, 'Xin Wudai shi 新五代史, annals juan 64 (ctext.org)', 'Ruled 31 years; famous for the seven-treasure chamber pots of the Shu court; surrendered to Song 965, died days after arriving at Kaifeng; his Song posthumous treatment is unsettled in sources — to verify'),
(170, 'Liu Yan', '刘龑 (originally Liu Yan 刘岩)', 'Gaozu 高祖', 'Tianhuang Dadi 天皇大帝', 917, 942, 32, NULL,
 'Xin Wudai shi 新五代史, annals juan 65 (ctext.org)', 'Claimed the imperial title 917; invented the character 龑 for his own name ("flying dragon in the sky"); cruel by his own analysis: "I am a dragon of the southern sea"'),
(171, 'Liu Bin', '刘玢', NULL, 'Shang 殇皇帝', 942, 943, 32, 170, 'Xin Wudai shi 新五代史, annals juan 65 (ctext.org)', 'Killed by his brother within a year'),
(172, 'Liu Sheng', '刘晟', 'Zhongzong 中宗', 'Wendi 文武光圣明孝皇帝', 943, 958, 32, 171, 'Xin Wudai shi 新五代史, annals juan 65 (ctext.org)', 'Usurped; took Chu lands 951; surrounded by suspicion, killed his brothers and even his own close kin'),
(173, 'Liu Chang', '刘鋹', NULL, 'Houzhu 后主 (Marquis of Enshe 恩赦侯)', 958, 971, 32, 172, 'Xin Wudai shi 新五代史, annals juan 66 (ctext.org)', 'Believed officials must be castrated to be loyal; surrendered to Song 971. Fourth state romanised "Han" in this database (汉， 蜀汉， 后汉， 南汉， 北汉) — name collision to handle in queries'),
(174, 'Wang Shenzhi', '王审知', 'Taizu 太祖', 'King Zhongyi 忠懿王', 909, 925, 33, NULL,
 'Xin Wudai shi 新五代史, annals juan 68 (ctext.org)', 'Min founder; a king, never an emperor; known as the "King who opened Min" 开闽王. Posthumous form to verify against the cited juan'),
(175, 'Wang Yanhan', '王延翰', NULL, 'none (deposed)', 925, 926, 33, 174, 'Xin Wudai shi 新五代史, annals juan 68 (ctext.org)', 'Called himself Grand Prince 大闽国王; killed by his brother'),
(176, 'Wang Yanjun', '王延钧 (renamed Wang Lin 王鏻)', 'Taizong 太宗', 'Huidi 惠皇帝', 926, 935, 33, 175,
 'Xin Wudai shi 新五代史, annals juan 68 (ctext.org)', 'First to claim the imperial title in Min, 933; killed by his own son. Temple name to verify against the cited juan'),
(177, 'Wang Chang', '王昶', 'Kangzong 康宗', 'none', 935, 939, 33, 176, 'Xin Wudai shi 新五代史, annals juan 68 (ctext.org)', 'Killed by Zhu Wenjin and Lian Chongyu in a coup. Temple name to verify against the cited juan'),
(178, 'Wang Xi', '王曦 (written 王延羲 before 939)', 'Jingzong 景宗', 'none', 939, 943, 33, 177, 'Xin Wudai shi 新五代史, annals juan 68 (ctext.org)', 'Renamed himself from Yanxi 延羲 to Xi 曦 in 939; killed 943. Temple name to verify against the cited juan'),
(179, 'Wang Yanzheng', '王延政', NULL, 'Fudi 恭懿? — Emperor of Yin 殷帝 (see note)', 943, 945, 33, 178,
 'Xin Wudai shi 新五代史, annals juan 68-69 (ctext.org)', 'Rival claimant: broke away as the state of Yin 殷 and claimed the imperial title 943-945 at Jianzhou; surrendered to Southern Tang 945. Counts once, under Min, with note'),
(180, 'Ma Yin', '马殷', NULL, 'King Wumu 武穆王', 907, 930, 34, NULL,
 'Xin Wudai shi 新五代史, annals juan 66 (ctext.org)', 'Copper-and-iron coin regime — Chu''s famous soft currency; a king, never emperor. Temple name to verify against the cited juan'),
(181, 'Ma Xisheng', '马希声', NULL, 'King Hengyang 衡阳王', 930, 932, 34, 180, 'Xin Wudai shi 新五代史, annals juan 66 (ctext.org)', 'Famously ordered "mourn him as the death of an ordinary man" for a rival warlord''s death; ate chicken during his own father''s mourning'),
(182, 'Ma Xifan', '马希范', NULL, 'King Wenzhao 文昭王', 932, 947, 34, 181, 'Xin Wudai shi 新五代史, annals juan 66 (ctext.org)', 'The Xizhou bronze-pillar covenant with the Man chiefs (940) is recorded; extravagance paid by new taxes'),
(183, 'Ma Xiguang', '马希广', NULL, 'King Fei 废王', 947, 950, 34, 182, 'Xin Wudai shi 新五代史, annals juan 66 (ctext.org)', 'Died in the brothers'' war against Ma Xi''e'),
(184, 'Ma Xi''e', '马希萼', NULL, 'none (deposed King of Chu)', 950, 950, 34, 183, 'Xin Wudai shi 新五代史, annals juan 66 (ctext.org)', 'Took Changsha with Southern Tang help; deposed months later by Ma Xichong'),
(185, 'Ma Xichong', '马希崇', NULL, 'none (surrendered)', 950, 951, 34, 184, 'Xin Wudai shi 新五代史, annals juan 66 (ctext.org)', 'Last Chu ruler; shipped north with the whole Ma clan; Chu ends 951'),
(186, 'Gao Jixing', '高季兴', NULL, 'King Wuxin 武信王', 924, 929, 35, NULL,
 'Xin Wudai shi 新五代史, annals juan 69 (ctext.org)', '"Thief commander" 高赖子 of Jingzhou — kept trade goods flowing back to Liang or Shu as it suited; never emperor. Temple and posthumous forms to verify'),
(187, 'Gao Conghui', '高从诲', NULL, 'King Wenxian 文献王', 929, 948, 35, 186, 'Xin Wudai shi 新五代史, annals juan 69 (ctext.org)', 'Returned stolen tribute; accepted vassalage from all the north as it suited'),
(188, 'Gao Baorong', '高保融', NULL, 'King Zhenyi 贞懿王', 948, 960, 35, 187, 'Xin Wudai shi 新五代史, annals juan 69 (ctext.org)', 'Backed the Song from the start'),
(189, 'Gao Baoxu', '高保勖', NULL, 'none', 960, 962, 35, 188, 'Xin Wudai shi 新五代史, annals juan 69 (ctext.org)', 'Two years, unremarkable'),
(190, 'Gao Jichong', '高继冲', NULL, 'none (last ruler)', 962, 963, 35, 189, 'Songshi 宋史, juan 482 (ctext.org)', 'Surrendered Jingnan to Song 963 — first of the Ten Kingdoms to go'),
(191, 'Liu Chong', '刘崇 (renamed Liu Min 刘旻)', 'Shizu 世祖', 'Shenwu 神武皇帝', 951, 954, 36, NULL,
 'Xin Wudai shi 新五代史, annals juan 70 (ctext.org)', 'Uncle of Later Han''s founder; refused to serve Later Zhou, founded Northern Han at Taiyuan as a Khitan vassal ("nephew emperor" to the Liao "uncle"). Temple/posthumous forms to verify'),
(192, 'Liu Chengjun', '刘承钧 (written 刘钧)', NULL, 'Xiaohe 孝和皇帝', 954, 968, 36, 191, 'Xin Wudai shi 新五代史, annals juan 70 (ctext.org)', 'Called the Liao emperor "father" too; died of anger and drink'),
(193, 'Liu Ji''en', '刘继恩', NULL, 'none', 968, 968, 36, 192, 'Xin Wudai shi 新五代史, annals juan 70 (ctext.org)', 'Adopted heir; murdered within months by the minister Hou Baquan'),
(194, 'Liu Jiyuan', '刘继元', NULL, 'none (surrendered)', 968, 979, 36, 193, 'Xin Wudai shi 新五代史, annals juan 70 / Songshi 宋史 (ctext.org)', 'Last Ten Kingdoms ruler; Taiyuan flooded and taken by Song Taizong 979; the city was then razed');
