-- Batch 9: Sui 581-618, Tang 618-907, Wu Zhou 690-705.
-- Sources: Suishu 隋书, Jiu Tangshu 旧唐书, Xin Tangshu 新唐书 (ctext.org).

INSERT INTO rulers (id, personal_name, personal_name_cn, temple_name, posthumous_name, year_start, year_end, dynasty_id, predecessor_id, source, note) VALUES
(115, 'Yang Jian', '杨坚', 'Gaozu 高祖', 'Wendi 文皇帝', 581, 604, 19, 88,
 'Suishu 隋书, annals juan 1-2 (ctext.org)', 'Received Northern Zhou''s abdication 581; reunited north and south 589 — model reign for Tang founders'),
(116, 'Yang Guang', '杨广', NULL, 'Yangdi 炀皇帝', 604, 618, 19, 115,
 'Suishu 隋书, annals juan 3-5 (ctext.org)', 'Grand Canal, Luoyang, three Korean campaigns. Posthumous names conflict: Tang court gave 炀 (deposed-standard), the loyalist Sui court at Luoyang gave 明 — the losing name is the one history kept'),
(117, 'Yang You', '杨侑', NULL, 'Gongdi 恭皇帝', 617, 618, 19, 116, 'Suishu 隋书, annals juan 5 (ctext.org)', 'Child, installed at Daxing by Li Yuan in Yangdi''s lifetime; abdicated to Li Yuan June 618'),
(118, 'Yang Tong', '杨侗', NULL, 'Huangtai Lord 皇泰主', 618, 619, 19, 117,
 'Jiu Tangshu 旧唐书 / Jiu Wudai shi 旧五代史 (ctext.org)', 'Rival Sui claimant at Luoyang under Wang Shichong, June 618 - May 619; killed when Wang took the throne (Zheng 郑). Counted by rule 2, flagged as contested. Earlier draft of this database said 621 — the spot-check (challenge 2) corrected it to 619'),
(119, 'Li Yuan', '李渊', 'Gaozu 高祖', 'Shenyao 神尧大圣大光孝皇帝', 618, 626, 20, 117, 'Jiu Tangshu 旧唐书, annals juan 1-2 (ctext.org)', 'Tang founder; displaced by his son Li Shimin in the Xuanwu Gate aftermath of 626'),
(120, 'Li Shimin', '李世民', 'Taizong 太宗', 'Wendi 文皇帝', 626, 649, 20, 119,
 'Jiu Tangshu 旧唐书, annals juan 2-3 (ctext.org)', 'Killed his brothers at Xuanwu Gate 626 and forced his father''s abdication — the guilt Tang historians had to manage; Zhenguan era 贞观 (see era_names) is the model "good reign"'),
(121, 'Li Zhi', '李治', 'Gaozong 高宗', 'Tianhuang 天皇大帝', 649, 683, 20, 120, 'Xin Tangshu 新唐书, annals juan 3 (ctext.org)', 'Power with Empress Wu after ~660 — the prelude to Wu Zhou'),
(122, 'Li Xian', '李显', 'Zhongzong 中宗', 'Xiaohe 孝和皇帝', 684, 710, 20, 121,
 'Xin Tangshu 新唐书, annals juan 4 (ctext.org)', 'One row, two reigns: first 684 (weeks), deposed by Wu Zetian; restored 705-710. Died 710 — widely believed poisoned by Empress Wei and Princess Anle'),
(123, 'Li Dan', '李旦', 'Ruizong 睿宗', 'Xuanzhen 玄真大圣大兴孝皇帝', 684, 712, 20, 122,
 'Xin Tangshu 新唐书, annals juan 5 (ctext.org)', 'One row, two reigns: first 684-690 as Wu Zetian''s figurehead, resigned the imperial title 690; restored 710-712'),
(124, 'Li Chongmao', '李重茂', NULL, 'Shang 殇皇帝', 710, 710, 20, 122,
 'Jiu Tangshu 旧唐书, annals juan 7 / Xin Tangshu juan 5 (ctext.org)', 'Child put up for weeks in 710 after Zhongzong''s death (predecessor id 122), then pushed aside in the Tanglong coup by Li Longji and Princess Taiping. Rarely counted; included by rule 2, flagged'),
(125, 'Li Longji', '李隆基', 'Xuanzong 玄宗', 'Zhidao 大圣大明孝皇帝', 712, 756, 20, 123,
 'Jiu Tangshu 旧唐书, annals juan 8-9 (ctext.org)', 'Succeeded Ruizong''s restoration (predecessor id 123). Kaiyuan flourishing 开元 (see era_names), then the An Lushan rebellion 755; abdicated in flight to Shu 756'),
(126, 'Li Heng', '李亨', 'Suzong 肃宗', 'Wenming 文明武德大圣大宣孝皇帝', 756, 762, 20, 125, 'Jiu Tangshu 旧唐书, annals juan 10 (ctext.org)', 'Proclaimed emperor in flight, 756. First of three rulers romanised Li Heng (李亨, 李恒 131, and a third below); keep the ids'),
(127, 'Li Yu', '李豫', 'Daizong 代宗', 'Ruiwen Xiaowu 睿文孝武皇帝', 762, 779, 20, 126, 'Jiu Tangshu 旧唐书, annals juan 11-12 (ctext.org)', 'An Lushan crushed 763 with Uyghur help; Tibetans briefly took Chang''an 763. Same romanisation as Li Yu 李煜 of Southern Tang (id 160)'),
(128, 'Li Kuo', '李适', 'Dezong 德宗', 'Shenwu Xiaowen 神武孝文皇帝', 779, 805, 20, 127,
 'Jiu Tangshu 旧唐书, annals juan 12-13 (ctext.org)', 'Note the tone: Kuo 适, not Song 诵 (id 129). Era Jianzhong 建中, then the Jingyuan mutiny'),
(129, 'Li Song', '李诵', 'Shunzong 顺宗', 'Daan Dasheng 安孝皇帝 (full: 大安大圣安孝皇帝)', 805, 805, 20, 128, 'Jiu Tangshu 旧唐书, annals juan 14 (ctext.org)', 'Reigned ~6 months (stroke), abdicated under the Yongzhen reform; died months later'),
(130, 'Li Chun', '李纯', 'Xianzong 宪宗', '昭文章武大圣至神孝皇帝 (Zhaowen Zhangwu Zhishen Xiaohuangdi)', 805, 820, 20, 129,
 'Jiu Tangshu 旧唐书, annals juan 14-15 (ctext.org)', 'Broke the regional commands (Huaixi 817); killed, apparently by eunuch Chen Hongzhi — first emperor killed by eunuchs'),
(131, 'Li Heng', '李恒', 'Muzong 穆宗', 'Ruisheng Wenhui 睿圣文惠孝皇帝', 820, 824, 20, 130, 'Jiu Tangshu 旧唐书, annals juan 16 (ctext.org)', 'Second Li Heng (first: Suzong 李亨, id 126); died after an elixir stroke, aged 30'),
(132, 'Li Zhan', '李湛', 'Jingzong 敬宗', 'Ruiwu 昭愍皇帝', 824, 826, 20, 131, 'Jiu Tangshu 旧唐书, annals juan 17 (ctext.org)', 'Killed by eunuch conspirators at a night drinking party, aged 18'),
(133, 'Li Ang', '李昂', 'Wenzong 文宗', 'Yuansheng Zhaoxian 元圣昭献孝皇帝', 826, 840, 20, 132, 'Jiu Tangshu 旧唐书, annals juan 17 (ctext.org)', 'The Sweet Dew incident 835: eunuchs massacred the court; he died a prisoner of his own guards'),
(134, 'Li Yan', '李炎', 'Wuzong 武宗', 'Zhaosu 至道昭肃孝皇帝', 840, 846, 20, 133, 'Jiu Tangshu 旧唐书, annals juan 18 (ctext.org)', 'Huichang persecution of Buddhism 845; personal name changed from Li Chan 李瀍 to Li Yan when enthroned'),
(135, 'Li Chen', '李忱', 'Xuanzong 宣宗', 'Shengwu Xianwen 圣武献文孝皇帝', 846, 859, 20, 134,
 'Jiu Tangshu 旧唐书, annals juan 18 (ctext.org)', 'Watch the romanisation: Xuanzong 宣宗 (this) vs Xuanzong 玄宗 (id 125) — written characters differ by one stroke, sound differs only in tone'),
(136, 'Li Cui', '李漼', 'Yizong 懿宗', 'Zhaosheng 昭圣恭惠孝皇帝', 859, 873, 20, 135, 'Jiu Tangshu 旧唐书, annals juan 19 (ctext.org)', 'Pang Xun mutiny 868, Huang Chao rising brewing; "the bud of the great disorder"'),
(137, 'Li Xuan', '李儇', 'Xizong 僖宗', 'Huisheng 惠圣恭定孝皇帝', 873, 888, 20, 136, 'Jiu Tangshu 旧唐书, annals juan 19 (ctext.org)', 'Huang Chao took Chang''an 881; the empire passed to warlords'),
(138, 'Li Ye', '李晔', 'Zhaozong 昭宗', 'Shengmu Jingwen 圣穆景文孝皇帝', 888, 904, 20, 137,
 'Jiu Tangshu 旧唐书, annals juan 20 (ctext.org)', 'Murdered on Zhu Wen''s order; personal name originally Li Min 李敏, changed to Ye 晔 889'),
(139, 'Li Zhu', '李柷', NULL, 'Aidi 哀皇帝 (Zhaoxuan 昭宣帝)', 904, 907, 20, 138, 'Jiu Tangshu 旧唐书, annals juan 20 (ctext.org)', 'Last Tang emperor; abdicated to Zhu Wen 907, poisoned 908'),
(140, 'Wu Zhao', '武曌 (given name 武则天 Wu Zetian)', NULL, 'Shengshen Huangdi 圣神皇帝 (Zetian Dasheng 则天大圣皇帝)', 690, 705, 21, 123,
 'Xin Tangshu 新唐书, annals juan 4 (ctext.org)', 'Only female sovereign in this range; took the throne from Ruizong''s first reign (predecessor id 123); her own state Wu Zhou 武周, capital Luoyang as Shendu 神都. Tang restored under Zhongzong 705; Wu Zetian was her self-chosen title, Zhao 曌 her invented character-name');
