-- Batch 12: Liao 916-1125, Northern Song 960-1127, Southern Song 1127-1279,
-- Western Xia 1038-1227, Jin 1115-1234. Rival states — years overlap.
-- Sources: Liaoshi 辽史, Songshi 宋史, Jinshi 金史 (ctext.org); Xia rows from
-- Songshi 宋史, juans 480-485 (ctext.org).
-- NOTE: rewritten 2026-09-29 after a PowerShell Get-Content/Set-Content
-- round-trip mangled the UTF-8 Chinese in the first version (see journal).

INSERT INTO rulers (id, personal_name, personal_name_cn, temple_name, posthumous_name, year_start, year_end, dynasty_id, predecessor_id, source, note) VALUES
(195, 'Yelü Abaoji', '耶律阿保机 (Yelü Yi 耶律亿)', 'Taizu 太祖', 'Shengtian Dasheng 大圣大明皇帝 (to verify)', 907, 926, 37, NULL,
 'Liaoshi 辽史, annals juan 1-2 (ctext.org)', 'Khitan khan from 907, emperor from 916 — hence two start dates; created the Khitan script. Posthumous form to verify'),
(196, 'Yelü Deguang', '耶律德光', 'Taizong 太宗', 'Xiaowu Huiwen 孝武惠文皇帝 (to verify)', 926, 947, 37, 195,
 'Liaoshi 辽史, annals juan 3-4 (ctext.org)', 'Took Kaifeng 947 and proclaimed himself emperor of China; retreated and died of illness on the road — "the Liao emperor who was China''s emperor for three months"'),
(197, 'Yelü Ruan', '耶律阮 (child name Wuyu 兀欲)', 'Shizong 世宗', 'Xiaohe Zhuangxian 孝和庄宪皇帝 (to verify)', 947, 951, 37, 196, 'Liaoshi 辽史, annals juan 5 (ctext.org)', 'Enthroned by troops against the declared heir; killed by a cousin''s mutiny'),
(198, 'Yelü Jing', '耶律璟', 'Muzong 穆宗', 'Xiaoan Jingzheng 孝安敬正皇帝 (to verify)', 951, 969, 37, 197, 'Liaoshi 辽史, annals juan 6 (ctext.org)', 'Slept all day, drank all night ("the sleeping emperor" 睡王); killed by kitchen servants'),
(199, 'Yelü Xian', '耶律贤', 'Jingzong 景宗', 'Kangjing 康靖 (to verify)', 969, 982, 37, 198, 'Liaoshi 辽史, annals juan 7-8 (ctext.org)', 'Sickly; power with Empress Xiao (Yanyan 萧燕燕) — the regency excluded by rule 3 but the power itself is the story'),
(200, 'Yelü Longxu', '耶律隆绪', 'Shengzong 圣宗', 'Wenwu Daxiaoxuan 文武大孝宣皇帝', 982, 1031, 37, 199, 'Liaoshi 辽史, annals juan 10-17 (ctext.org)', 'Chanyuan covenant with Song 1005 (annual silver and silk); the Liao high point'),
(201, 'Yelü Zongzhen', '耶律宗真', 'Xingzong 兴宗', 'to verify', 1031, 1055, 37, 200, 'Liaoshi 辽史, annals juan 18-20 (ctext.org)', 'Demanded the word 兄 in the 1042 treaty squeeze; Buddhist excesses'),
(202, 'Yelü Hongji', '耶律洪基', 'Daozong 道宗', 'Rentian Dafu 仁天大孝文皇帝 (to verify)', 1055, 1101, 37, 201, 'Liaoshi 辽史, annals juan 21-26 (ctext.org)', 'Executed his empress on a false adultery case (Yelü Yixin); the corruption begin of the Liao fall'),
(203, 'Yelü Yanxi', '耶律延禧', NULL, 'Tianzuo Tiandi 天祚帝', 1101, 1125, 37, 202, 'Liaoshi 辽史, annals juan 29-30 (ctext.org)', 'Last Liao emperor; fled the Jurchen collapse 1124, captured 1125'),
(204, 'Zhao Kuangyin', '赵匡胤', 'Taizu 太祖', NULL, 960, 976, 38, 154,
 'Songshi 宋史, annals juan 1-3 (ctext.org)', 'Chenqiao mutiny 960, yellow robe; predecessor link runs to Chai Zongxun (id 154) across dynasties, per design rule 4. Died at 50 with no deathbed record — the "shadow of the axe" mystery (烛影斧声)'),
(205, 'Zhao Guangyi', '赵光义', 'Taizong 太宗', NULL, 976, 997, 38, 204, 'Songshi 宋史, annals juan 4-5 (ctext.org)', 'Took the throne before his brother''s sons were grown ("the golden casket covenant" 金匮之盟 as cover); defeated at Gaolianghe 979 by the Liao'),
(206, 'Zhao Heng', '赵恒', 'Zhenzong 真宗', NULL, 997, 1022, 38, 205, 'Songshi 宋史, annals juan 6-8 (ctext.org)', 'Chanyuan covenant 1005; staged the "heavenly letters" (天书) to legitimise himself — state-sponsored superstition'),
(207, 'Zhao Zhen', '赵祯', 'Renzong 仁宗', NULL, 1022, 1063, 38, 206, 'Songshi 宋史, annals juan 9-13 (ctext.org)', 'No son; his 42-year reign is the Qingli era of Fan Zhongyan and the literary golden age'),
(208, 'Zhao Shu', '赵曙', 'Yingzong 英宗', NULL, 1063, 1067, 38, 207, 'Songshi 宋史, annals juan 13-14 (ctext.org)', 'The Puyi of his day: the "protocol controversy" (濮议) over honouring his dead birth father'),
(209, 'Zhao Xu', '赵顼', 'Shenzong 神宗', NULL, 1067, 1085, 38, 208, 'Songshi 宋史, annals juan 14-16 (ctext.org)', 'Wang Anshi reforms (Xining 变法); same romanisation as Zhezong 赵煦 below — 顼/煦'),
(210, 'Zhao Xu', '赵煦', 'Zhezong 哲宗', NULL, 1085, 1100, 38, 209, 'Songshi 宋史, annals juan 17-18 (ctext.org)', 'Repealed then partially restored the reforms; two emperors romanised Zhao Xu in a row (ids 209-210) — the name trap is real'),
(211, 'Zhao Ji', '赵佶', 'Huizong 徽宗', NULL, 1100, 1126, 38, 210,
 'Songshi 宋史, annals juan 19-22 (ctext.org)', 'The artist-emperor (slender-gold script); taken to the north as a captive at Jingkang 1127, died in the Wuguo city 五国城'),
(212, 'Zhao Huan', '赵桓', 'Qinzong 钦宗', NULL, 1126, 1127, 38, 211, 'Songshi 宋史, annals juan 23 (ctext.org)', 'Reigned one year in the fall of Kaifeng; shared his brother''s captivity, died 1156 in the north'),
(213, 'Zhao Gou', '赵构', 'Gaozong 高宗', NULL, 1127, 1162, 39, 212,
 'Songshi 宋史, annals juan 24-27 (ctext.org)', 'Restored the Song at Lin''an after the Jingkang collapse; recalled Yue Fei''s northern campaign to sign the Shaoxing peace with the Jin'),
(214, 'Zhao Shen', '赵昚', 'Xiaozong 孝宗', NULL, 1162, 1189, 39, 213, 'Songshi 宋史, annals juan 33-35 (ctext.org)', 'Restored Yue Fei''s reputation; the second-best reign of Southern Song by common judgment'),
(215, 'Zhao Dun', '赵惇', 'Guangzong 光宗', NULL, 1189, 1194, 39, 214, 'Songshi 宋史, annals juan 36 (ctext.org)', 'Sided with his empress against his father; deposed by ministers and dowager'),
(216, 'Zhao Kuo', '赵扩', 'Ningzong 宁宗', NULL, 1194, 1224, 39, 215, 'Songshi 宋史, annals juan 37-41 (ctext.org)', 'Same romanisation as the Warring States general Zhao Kuo 赵括 ("talking war"); the Han Tuozhou, then Shi Miyuan regencies'),
(217, 'Zhao Yun', '赵昀', 'Lizong 理宗', NULL, 1224, 1264, 39, 216, 'Songshi 宋史, annals juan 41-45 (ctext.org)', 'Same romanisation as the general Zhao Yun 赵云; endorsed Neo-Confucianism as state learning; joined the Mongols to destroy Jin 1234 — then met them'),
(218, 'Zhao Qi', '赵禥', 'Duzong 度宗', NULL, 1264, 1274, 39, 217, 'Songshi 宋史, annals juan 46 (ctext.org)', 'Delegated to Jia Sidao while the Mongols prepared the final assault'),
(219, 'Zhao Xian', '赵㬎', NULL, 'Gongdi 恭皇帝 (Yingguo Gong 瀛国公)', 1274, 1276, 39, 218, 'Songshi 宋史, annals juan 47 (ctext.org)', 'Surrendered Lin''an at 4; became a Tibetan Buddhist monk in the north — later rumour linked his line to Yuan Shundi (recorded, not believed)'),
(220, 'Zhao Shi', '赵昰', NULL, 'Duanzong 端宗', 1276, 1278, 39, 219, 'Songshi 宋史, annals juan 47 (ctext.org)', 'Court in exile at Fuzhou; died fleeing by sea'),
(221, 'Zhao Bing', '赵昺', NULL, 'none — last emperor', 1278, 1279, 39, 220,
 'Songshi 宋史, annals juan 47 (ctext.org)', 'Eight years old when Lu Xiufu leapt with him into the sea at Yashan 崖山 1279 — the Song ends, the empire of "all under heaven" briefly Mongol'),
(222, 'Li Yuanhao', '李元昊 (self-renamed Nangxiao 曩霄 1038)', 'Jingzong 景宗', 'Wulie 武烈皇帝', 1038, 1048, 40, NULL,
 'Songshi 宋史, juans 480-485 (ctext.org)', 'Took the imperial title 1038 in Tangut script; forced the Song to recognise him and pay "subsidies" (岁币) after 1040-1042 wars; killed by his son'),
(223, 'Li Liangzuo', '李谅祚', 'Yizong 毅宗', 'Zhaoying 昭英? (to verify)', 1048, 1067, 40, 222, 'Songshi 宋史, juans 480-485 (ctext.org)', 'Infant accession; his uncle Nozang seized, then lost, power'),
(224, 'Li Bingchang', '李秉常', 'Huizong 惠宗', 'Kangjing 康靖? (to verify)', 1067, 1086, 40, 223, 'Songshi 宋史, juans 480-485 (ctext.org)', 'Pro-Han policy split the court; his mother''s Liang clan held the regency'),
(225, 'Li Qianshun', '李乾顺', 'Chongzong 崇宗', 'Shengwen 圣文皇帝', 1086, 1139, 40, 224, 'Songshi 宋史, juans 480-485 (ctext.org)', 'Played Jin and Song against each other to take the Shaanxi fringe'),
(226, 'Li Renxiao', '李仁孝', 'Renzong 仁宗', 'Shengde 圣德皇帝', 1139, 1193, 40, 225, 'Songshi 宋史, juans 480-485 (ctext.org)', 'Longest Xia reign; sponsored Tangut-Buddhist printing; Ren rule said to be the Xia high point'),
(227, 'Li Chunyou', '李纯祐', 'Huanzong 桓宗', 'Zhaojian 昭简? (to verify)', 1193, 1206, 40, 226, 'Songshi 宋史, juans 480-485 (ctext.org)', 'Deposed by his cousin Li Anquan — the Xia decline begins'),
(228, 'Li Anquan', '李安全', 'Xiangzong 襄宗', 'Jingmu 敬穆? (to verify)', 1206, 1211, 40, 227, 'Songshi 宋史, juans 480-485 (ctext.org)', 'Swung Xia to the Mongols, then Genghis turned on him; died unexplainedly'),
(229, 'Li Zunxu', '李遵顼', 'Shenzong 神宗', 'Yingwen 英文? (to verify)', 1211, 1223, 40, 228, 'Songshi 宋史, juans 480-485 (ctext.org)', 'Abdicated to his son under Mongol pressure — the only Xia ruler to give up the throne alive'),
(230, 'Li Dewang', '李德旺', 'Xianzong 献宗', 'none', 1223, 1226, 40, 229, 'Songshi 宋史, juans 480-485 (ctext.org)', 'Tried to back out of the Mongol alliance; Genghis''s last campaign was aimed at him'),
(231, 'Li Xian', '李睍', NULL, 'none (last ruler)', 1226, 1227, 40, 230, 'Songshi 宋史, juans 480-485 (ctext.org)', 'Surrendered as Genghis Khan died; Xia ends 1227'),
(232, 'Wanyan Aguda', '完颜阿骨打 (Wanyan Min 完颜旻)', 'Taizu 太祖', 'Yuanxing 应兴? (to verify)', 1115, 1123, 41, NULL,
 'Jinshi 金史, annals juan 1-2 (ctext.org)', 'Jurchen founder; destroyed the Liao order with 2,500 men at Chuhedian 1114; created the Jurchen script'),
(233, 'Wanyan Wuqimai', '完颜吴乞买 (Wanyan Sheng 完颜晟)', 'Taizong 太宗', 'Wenlie 文烈? (to verify)', 1123, 1135, 41, 232, 'Jinshi 金史, annals juan 3 (ctext.org)', 'Destroyed Liao 1125 and Northern Song 1127; brother succession, then adopted the Chinese-style transfer of power to a son — court crisis'),
(234, 'Wanyan Dan', '完颜亶', 'Xizong 熙宗', 'Wuzhen 武臻? (to verify)', 1135, 1149, 41, 233, 'Jinshi 金史, annals juan 4 (ctext.org)', 'Brought Chinese statecraft; murdered in his bed by Wanyan Liang — the "Hailing prince"'),
(235, 'Wanyan Liang', '完颜亮', NULL, 'Prince Hailing 海陵王 (deposed)', 1149, 1161, 41, 234,
 'Jinshi 金史, annals juan 5 / juan 129 (ctext.org)', 'Usurper, capital to Yanjing 1153 (now Beijing), destroyed by his own officers on the Yangzi during the invasion of Song 1161; posthumously denied the imperial title'),
(236, 'Wanyan Yong', '完颜雍', 'Shizong 世宗', 'Guangtian Xingyun 光天兴运文武睿孝? (to verify)', 1161, 1189, 41, 235, 'Jinshi 金史, annals juan 6-8 (ctext.org)', 'The "Yao-Shun little ruler" 小尧舜; Jurchen revival and peace with Song (Longxing treaty 1164)'),
(237, 'Wanyan Jing', '完颜璟', 'Zhangzong 章宗', 'Xiangao 绍武? (to verify)', 1189, 1208, 41, 236, 'Jinshi 金史, annals juan 9-12 (ctext.org)', 'Literary peak and flooding Yellow River; no son — hence the crisis of 1208-1213'),
(238, 'Wanyan Yongji', '完颜永济', NULL, 'Shaowei 卫绍王 (deposed)', 1208, 1213, 41, 237, 'Jinshi 金史, annals juan 13 (ctext.org)', 'Installed by Empress Li; Genghis Khan learned who he was ("a mediocrity") and attacked; strangled in a coup'),
(239, 'Wanyan Xun', '完颜珣', 'Xuanzong 宣宗', 'Jixian 继天兴统? (to verify)', 1213, 1224, 41, 238, 'Jinshi 金史, annals juan 14-17 (ctext.org)', 'Capital moved from Zhongdu to Kaifeng 1214 (贞祐南迁) — abandoning the north to the Mongols'),
(240, 'Wanyan Shouxu', '完颜守绪', 'Aizong 哀宗', 'Zhuangsheng 敬哀? (to verify)', 1224, 1234, 41, 239, 'Jinshi 金史, annals juan 17-18 (ctext.org)', 'Sustained resistance to the Mongols; suicide at Caizhou 1234 as the city fell'),
(241, 'Wanyan Chenglin', '完颜承麟', NULL, 'Modi 末帝', 1234, 1234, 41, 240,
 'Jinshi 金史, annals juan 18 (ctext.org)', 'Made emperor on the morning the city fell; killed in the afternoon — shortest reign in Chinese history (hours), counted here by rule 2');
