-- Batch 1: all dynasties/states, Qin (221 BCE) to Qing (1912 CE).
-- Sources: the standard history of each state, cited by juan.

INSERT INTO dynasties (id, name, name_cn, year_start, year_end, capital, source, note) VALUES
(1,  'Qin',           '秦',    -221,  -206, 'Xianyang 咸阳',        'Shiji 史记, juan 6 (ctext.org)', 'First state to use the title huangdi 皇帝; collapsed three years after Shi Huang''s death'),
(2,  'Western Han',   '西汉',  -202,      9, 'Chang''an 长安',       'Hanshu 汉书, juans 1-12 (ctext.org)', 'Liu Bang proclaimed emperor in -202; -206 is the fall of Qin. Two minor claimants (Shaodi) omitted'),
(3,  'Xin',           '新',       9,     23, 'Chang''an 长安',       'Hanshu 汉书, juan 99 (ctext.org)', 'Usurpation by Wang Mang 王莽'),
(4,  'Eastern Han',   '东汉',     25,    220, 'Luoyang 洛阳',         'Hou Hanshu 后汉书, annals (ctext.org)', 'Restored by Liu Xiu (Guangwu) after the Red Eyebrows / Gengshi interregnum'),
(5,  'Wei',           '魏',      220,    266, 'Luoyang 洛阳',         'Sanguozhi 三国志, Wei shu (ctext.org)', 'Cao Pi received the abdication of Han Xiandi in the 12th month of 220'),
(6,  'Shu Han',       '蜀汉',    221,    263, 'Chengdu 成都',         'Sanguozhi 三国志, Shu shu (ctext.org)', 'Liu Bei claimed to continue the Han; fell to Wei in 263'),
(7,  'Wu',            '吳',      229,    280, 'Jianye 建业',          'Sanguozhi 三国志, Wu shu (ctext.org)', 'Sun Quan took the imperial title in 229, having been king from 222'),
(8,  'Western Jin',   '西晋',    265,    316, 'Luoyang 洛阳',         'Jinshu 晋书, juans 1-5 (ctext.org)', 'Sima Yan received Wei''s abdication in the 12th month of 265 (era Taishi 泰始 began 266)'),
(9,  'Eastern Jin',   '东晋',    317,    420, 'Jiankang 建康',        'Jinshu 晋书, juans 6-10 (ctext.org)', 'Sima Rui proclaimed emperor at Jiankang after the fall of the north'),
(10, 'Northern Wei',  '北魏',    386,    534, 'Pingcheng 平城, Luoyang 洛阳', 'Weishu 魏书, annals (ctext.org)', 'Tuoba Gui; capital moved to Luoyang 494; split 534-535 into Eastern and Western Wei'),
(11, 'Eastern Wei',   '东魏',    534,    550, 'Ye 邺',                'Weishu 魏书, juan 12 (ctext.org)', 'Puppet state of the Gao clan; one emperor (Xiaojing)'),
(12, 'Western Wei',   '西魏',    535,    557, 'Chang''an 长安',       'Beishi 北史, juan 5 (ctext.org)', 'Puppet state of the Yuwen clan; three emperors'),
(13, 'Northern Qi',   '北齊',    550,    577, 'Ye 邺',                'Beiqi shu 北齐书, annals (ctext.org)', 'Gao Yang received Eastern Wei''s abdication; fell to Northern Zhou 577'),
(14, 'Northern Zhou','北周',    557,    581, 'Chang''an 长安',       'Zhoushu 周书, annals (ctext.org)', 'Yuwen clan; Yang Jian ruled as regent from 580, took the throne 581'),
(15, 'Liu Song',     '劉宋',    420,    479, 'Jiankang 建康',        'Songshu 宋书, annals (ctext.org)', 'Liu Yu received Eastern Jin''s abdication'),
(16, 'Southern Qi',  '南齊',    479,    502, 'Jiankang 建康',        'Nan Qi shu 南齐书, annals (ctext.org)', 'Xiao Daocheng; seven emperors in 23 years'),
(17, 'Liang',        '梁',      502,    557, 'Jiankang 建康',        'Liangshu 梁书, annals (ctext.org)', 'Xiao Yan (Wudi); collapsed amid the Hou Jing rebellion'),
(18, 'Chen',         '陳',      557,    589, 'Jiankang 建康',        'Chenshu 陈书, annals (ctext.org)', 'Last of the southern dynasties; fell to Sui 589'),
(19, 'Sui',          '隋',      581,    618, 'Daxing 大兴 (Chang''an)', 'Suishu 隋书, annals (ctext.org)', 'Yang Jian received Northern Zhou''s abdication; reunified China 589'),
(20, 'Tang',         '唐',      618,    907, 'Chang''an 长安',       'Jiu Tangshu 旧唐书 / Xin Tangshu 新唐书, annals (ctext.org)', 'Li Yuan; interrupted 690-705 by Wu Zhou'),
(21, 'Wu Zhou',      '武周',    690,    705, 'Luoyang 神都',         'Xin Tangshu 新唐书, juan 4 (ctext.org)', 'Wu Zetian 武则天, the only ruling female sovereign; Tang restored 705'),
(22, 'Later Liang',  '后梁',    907,    923, 'Kaifeng 开封',         'Jiu Wudai shi 旧五代史, annals (ctext.org)', 'Zhu Wen ended the Tang; first of the Five Dynasties'),
(23, 'Later Tang',   '后唐',    923,    936, 'Luoyang 洛阳',         'Jiu Wudai shi 旧五代史, annals (ctext.org)', 'Li Cunxu (Shatuo Turk) claimed to restore the Tang'),
(24, 'Later Jin',    '后晋',    936,    947, 'Kaifeng 开封',         'Jiu Wudai shi 旧五代史, annals (ctext.org)', 'Shi Jingtang, installed with Khitan help; ceded the Sixteen Prefectures'),
(25, 'Later Han',    '后汉',    947,    951, 'Kaifeng 开封',         'Jiu Wudai shi 旧五代史, annals (ctext.org)', 'Liu Zhiyuan; shortest of the Five Dynasties'),
(26, 'Later Zhou',   '后周',    951,    960, 'Kaifeng 开封',         'Jiu Wudai shi 旧五代史 / Songshi 宋史 (ctext.org)', 'Ended when Zhao Kuangyin staged the Chenqiao mutiny and founded the Song'),
(27, 'Yang Wu',     '楊吳',    902,    937, 'Jiangdu 江都 (Yangzhou)', 'Xin Wudai shi 新五代史, annals (ctext.org)', 'Yang Xingmi''s state; rulers were mostly kings; absorbed by Southern Tang 937'),
(28, 'Southern Tang','南唐',    937,    976, 'Jinling 金陵',         'Xin Wudai shi 新五代史, annals (ctext.org)', 'Li Bian (Xu Zhigao); Li Yu, the poet-emperor, surrendered to Song 975/976'),
(29, 'Wuyue',        '吳越',    907,    978, 'Hangzhou 杭州',        'Xin Wudai shi 新五代史, annals (ctext.org)', 'Kings only — never claimed the imperial title; peaceful surrender to Song 978'),
(30, 'Former Shu',   '前蜀',    907,    925, 'Chengdu 成都',         'Xin Wudai shi 新五代史, annals (ctext.org)', 'Wang Jian claimed the imperial title in 907'),
(31, 'Later Shu',    '后蜀',    934,    965, 'Chengdu 成都',         'Xin Wudai shi 新五代史, annals (ctext.org)', 'Meng Zhixiang; two rulers'),
(32, 'Southern Han', '南漢',    917,    971, 'Xingwang 興王府 (Guangzhou)', 'Xin Wudai shi 新五代史, annals (ctext.org)', 'Liu Yan proclaimed emperor 917; infamous for eunuch government'),
(33, 'Min',          '閩',      909,    945, 'Fuzhou 福州',          'Xin Wudai shi 新五代史, annals (ctext.org)', 'Wang Shenzhi was king; Wang Yanjun claimed the imperial title 933'),
(34, 'Chu',          '楚',      907,    951, 'Tanzhou 潭州 (Changsha)', 'Xin Wudai shi 新五代史, annals (ctext.org)', 'Kings only; submitted to Later Liang/Tang'),
(35, 'Jingnan',      '南平',    924,    963, 'Jiangling 江陵',       'Xin Wudai shi 新五代史, annals (ctext.org)', 'Smallest of the Ten Kingdoms; kings only'),
(36, 'Northern Han', '北漢',    951,    979, 'Taiyuan 太原',         'Xin Wudai shi 新五代史 / Songshi 宋史 (ctext.org)', 'Liu Chong claimed to continue Later Han; Khitan vassal; last of the Ten Kingdoms'),
(37, 'Liao',         '遼',      916,   1125, 'Shangjing 上京',       'Liaoshi 辽史, annals (ctext.org)', 'Yelü Abaoji proclaimed khan 907, emperor 916; Khitan state, name varied between Liao/Khitan'),
(38, 'Northern Song','北宋',    960,   1127, 'Kaifeng 开封',         'Songshi 宋史, annals (ctext.org)', 'Zhao Kuangyin; ended with the Jingkang incident, fall of Kaifeng'),
(39, 'Southern Song','南宋',   1127,   1279, 'Lin''an 临安',         'Songshi 宋史, annals (ctext.org)', 'Zhao Gou; fell to the Mongols 1279'),
(40, 'Western Xia',  '西夏',   1038,   1227, 'Xingqing 兴庆',        'Songshi 宋史, juans 480-485 (ctext.org)', 'Tangut state; Li Yuanhao took the imperial title 1038; destroyed by the Mongols 1227'),
(41, 'Jin',          '金',     1115,   1234, 'Huining 会宁, Zhongdu 中都, Kaifeng 开封', 'Jinshi 金史, annals (ctext.org)', 'Wanyan Aguda; destroyed Liao 1125 and Northern Song 1127; destroyed by Mongols 1234'),
(42, 'Yuan',         '元',    1271,   1368, 'Dadu 大都 (Beijing)',  'Yuanshi 元史, annals (ctext.org)', 'Kublai proclaimed the dynasty name 1271; Mongol rule of China to 1368'),
(43, 'Ming',         '明',    1368,   1644, 'Nanjing 南京, Beijing 北京', 'Mingshi 明史, annals (ctext.org)', 'Zhu Yuanzhang; capital moved to Beijing by Yongle; ended with Li Zicheng''s capture of Beijing'),
(44, 'Qing',         '清',    1636,   1912, 'Beijing 北京',         'Qingshi gao 清史稿, annals', 'Nurhaci founded Later Jin 1616, Huang Taiji renamed it Qing 1636; ruled China proper from 1644; last emperor abdicated 12 Feb 1912');
