-- Batch 7: Northern dynasties — Northern Wei 386-534, Eastern Wei, Western Wei,
-- Northern Qi, Northern Zhou (to 581).
-- Sources: Weishu 魏书, Beishi 北史, Beiqi shu 北齐书, Zhoushu 周书 (ctext.org).

INSERT INTO rulers (id, personal_name, personal_name_cn, temple_name, posthumous_name, year_start, year_end, dynasty_id, predecessor_id, source, note) VALUES
(59, 'Tuoba Gui', '拓跋珪', 'Taizu 太祖', 'Daowu 道武帝', 386, 409, 10, NULL,
 'Weishu 魏书, annals juan 2 (ctext.org)', 'Re-founded the Tuoba state as Wei at Shengle, then Pingcheng; killed by his son Tuoba Shao'),
(60, 'Tuoba Si', '拓跋嗣', 'Taizong 太宗', 'Mingyuan 明元帝', 409, 423, 10, 59, 'Weishu 魏书, annals juan 3 (ctext.org)', 'Took the Henan buffer from Liu Song 422-423'),
(61, 'Tuoba Tao', '拓跋焘', 'Shizu 世祖', 'Taiwu 太武帝', 423, 452, 10, 60, 'Weishu 魏书, annals juan 4 (ctext.org)', 'United the north 439; persecution of Buddhism 446; killed by eunuch Zong Ai'),
(62, 'Tuoba Yu', '拓跋余', NULL, 'none — Prince of Nan''an 南安王', 452, 452, 10, 61,
 'Weishu 魏书, annals juan 5 / juan 94 (ctext.org)',
 'Enthroned by Zong Ai after killing Taiwu; killed by Zong Ai months later. No posthumous imperial name (recorded only as Prince of Nan''an 南安王). Counted by rule 2, flagged'),
(63, 'Tuoba Jun', '拓跋濬', 'Gaozong 高宗', 'Wencheng 文成帝', 452, 465, 10, 62, 'Weishu 魏书, annals juan 5 (ctext.org)', 'Zong Ai executed; Buddhism restored; Yungang caves begun 460'),
(64, 'Tuoba Hong', '拓跋弘', 'Xianzu 显祖', 'Xianwen 献文帝', 465, 471, 10, 63, 'Weishu 魏书, annals juan 6 (ctext.org)', 'Abdicated to his 4-year-old son 471, kept power as retired emperor; died 476 in Empress Dowager Feng''s custody'),
(65, 'Yuan Hong', '元宏 (born Tuoba Hong 拓跋宏)', 'Gaozu 高祖', 'Xiaowen 孝文帝', 471, 499, 10, 64,
 'Weishu 魏书, annals juan 7 (ctext.org)', 'Great siniciser: clan names changed from Tuoba to Yuan 496, court language to Chinese, capital moved to Luoyang 494 — hence two personal names for one man'),
(66, 'Yuan Ke', '元恪', 'Shizong 世宗', 'Xuanwu 宣武帝', 499, 515, 10, 65, 'Weishu 魏书, annals juan 8 (ctext.org)', 'Under him the Wei took Hanzhong and Shouyang from the south'),
(67, 'Yuan Xu', '元诩', 'Suzong 肃宗', 'Xiaoming 孝明帝', 515, 528, 10, 66, 'Weishu 魏书, annals juan 9 (ctext.org)', 'Poisoned by his mother Empress Dowager Ling over his plan to strip her regency — trigger of the collapse'),
(68, 'Yuan Zhao', '元钊', NULL, 'none (infant)', 528, 528, 10, 67,
 'Weishu 魏书, annals juan 9 / juan 13 (ctext.org)',
 'Aged ~3, enthroned by Empress Dowager Ling disguised as a boy — succeeded by nothing but the Heyin massacre. Rarely counted; included by rule 2, flagged as contested'),
(69, 'Yuan Ziyou', '元子攸', 'Jingzong 敬宗', 'Xiaozhuang 孝庄帝', 528, 530, 10, 68,
 'Weishu 魏书, annals juan 10 (ctext.org)', 'Installed by Erzhu Rong after the Heyin massacre (2,000 courtiers killed); strangled Erzhu Rong himself in 530, then killed by the Erzhu clan'),
(70, 'Yuan Ye', '元晔', NULL, 'deposed, Prince of Changguang 长广王', 530, 531, 10, 69, 'Weishu 魏书, annals juan 11 (ctext.org)', 'Puppet of the Erzhu; deposed within months'),
(71, 'Yuan Gong', '元恭', NULL, 'Jiemin 节闵帝', 531, 532, 10, 70, 'Weishu 魏书, annals juan 11 (ctext.org)', 'Puppet of Erzhu Shilong; forced to suicide by Gao Huan 532'),
(72, 'Yuan Lang', '元朗', NULL, 'deposed, Prince of Anding 安定王', 531, 532, 10, 70,
 'Weishu 魏书, annals juan 11 (ctext.org)', 'Rival puppet installed by Gao Huan while Yuan Gong still sat at Luoyang — two "emperors" at once in 531-532; kept here with note'),
(73, 'Yuan Xiu', '元修', NULL, 'Xiaowu 孝武帝', 532, 534, 10, 72,
 'Weishu 魏书, annals juan 11 / Beishi 北史 juan 5 (ctext.org)', 'Fled from Gao Huan to Guanxi under Yuwen Tai 534 — the Wei splits into Eastern and Western; Yuwen Tai had him poisoned 534/535'),
(74, 'Yuan Shanjian', '元善见', NULL, 'Xiaojing 孝静帝', 534, 550, 11, 73, 'Weishu 魏书, annals juan 12 (ctext.org)', 'Moved to Ye by Gao Huan; forced to abdicate to Gao Yang 550 — one emperor, one state'),
(75, 'Yuan Baoju', '元宝炬', NULL, 'Wendi 文皇帝', 535, 551, 12, 73, 'Beishi 北史, juan 5 (ctext.org)', 'Western Wei founder; a placeholder for Yuwen Tai''s power'),
(76, 'Yuan Qin', '元钦', NULL, 'deposed (Feidi 废帝)', 551, 554, 12, 75, 'Beishi 北史, juan 5 (ctext.org)', 'Tried to recover power from Yuwen Tai; deposed and killed'),
(77, 'Tuoba Kuo', '拓跋廓', NULL, 'Gongdi 恭皇帝', 554, 557, 12, 76,
 'Beishi 北史, juan 5 (ctext.org)', 'Clan name changed back from Yuan to Tuoba 554; abdicated to Yuwen Jue 557, killed weeks later'),
(78, 'Gao Yang', '高洋', 'Xianzu 显祖', 'Wenxuan 文宣帝', 550, 559, 13, 74, 'Beiqi shu 北齐书, annals juan 4 (ctext.org)', 'Received Eastern Wei''s abdication; alternated brilliance and violent drunkenness'),
(79, 'Gao Yin', '高殷', NULL, 'Feidi 废帝 (Prince of Jinan 济南王)', 559, 560, 13, 78, 'Beiqi shu 北齐书, annals juan 5 (ctext.org)', 'Deposed by his uncle Gao Yan after a year; killed 561'),
(80, 'Gao Yan', '高演', 'Suzu 肃宗', 'Xiaozhao 孝昭帝', 560, 561, 13, 79, 'Beiqi shu 北齐书, annals juan 6 (ctext.org)', 'The capable brother; died after a fall from horseback, aged 26'),
(81, 'Gao Zhan', '高湛', 'Shizu 世祖', 'Wucheng 武成帝', 561, 565, 13, 80, 'Beiqi shu 北齐书, annals juan 7 (ctext.org)', 'Abdicated to his 9-year-old son in 565 but kept ruling until his death 569'),
(82, 'Gao Wei', '高纬', NULL, 'Houzhu 后主', 565, 577, 13, 81, 'Beiqi shu 北齐书, annals juan 8 (ctext.org)', 'Executed his best general Hulü Guang 572; lost Ye to Northern Zhou 577, fled, captured'),
(83, 'Gao Heng', '高恒', NULL, 'Youzhu 幼主', 577, 577, 13, 82, 'Beiqi shu 北齐书, annals juan 8 (ctext.org)', 'Child emperor for ~1 month in 577 while the state fell; reigned weeks, then both were executed'),
(84, 'Yuwen Jue', '宇文觉', NULL, 'Xiaomin 孝闵帝', 557, 557, 14, 77,
 'Zhoushu 周书, annals juan 3 / Beishi 北史 juan 9 (ctext.org)', 'Received Western Wei''s abdication aged 14; killed by cousin Yuwen Hu months later; no imperial temple/posthumous names given by the Zhou court'),
(85, 'Yuwen Yu', '宇文毓', 'Shizong 世宗', 'Ming 明帝', 557, 560, 14, 84, 'Zhoushu 周书, annals juan 4 (ctext.org)', 'Poisoned by Yuwen Hu'),
(86, 'Yuwen Yong', '宇文邕', 'Gaozu 高祖', 'Wudi 武皇帝', 560, 578, 14, 85, 'Zhoushu 周书, annals juan 5-6 (ctext.org)', 'Killed Yuwen Hu 572, destroyed Northern Qi 577, banned Buddhism 574; died on campaign aged 35'),
(87, 'Yuwen Yun', '宇文赟', 'Gaozong 高宗', 'Xuan 宣帝', 578, 579, 14, 86, 'Zhoushu 周书, annals juan 7 (ctext.org)', 'Abdicated to his 6-year-old son after a year of terror; died 580 aged 21'),
(88, 'Yuwen Chan', '宇文阐', NULL, 'Jing 静帝', 579, 581, 14, 87, 'Zhoushu 周书, annals juan 8 (ctext.org)', 'Abdicated to Yang Jian (Sui) 581; quietly killed soon after — the pattern of the abdication coup, 6th repetition');
