-- Batch 13: Yuan 1271-1368, Ming 1368-1644, Qing 1636-1912.
-- Sources: Yuanshi 元史, Mingshi 明史, Qingshi gao 清史稿 (ctext.org).
-- NOTE: rewritten 2026-09-29 after a PowerShell Get-Content/Set-Content
-- round-trip mangled the UTF-8 Chinese in the first version (see journal).

INSERT INTO rulers (id, personal_name, personal_name_cn, temple_name, posthumous_name, year_start, year_end, dynasty_id, predecessor_id, source, note) VALUES
(242, 'Kublai Khan', '忽必烈', 'Shizu 世祖', 'Shengde Shen Gong Wendi 圣德神功文武皇帝', 1260, 1294, 42, NULL,
 'Yuanshi 元史, annals juan 3-17 (ctext.org)', 'Mongol khagan from 1260; proclaimed the dynasty name Da Yuan 大元 1271 (borrowed from the Yijing: 大哉乾元); took Lin''an 1276, Song ends 1279. Khans before him (Genghis to Möngke) are out of scope here — see design doc'),
(243, 'Temür', '铁穆耳 (Temür Öljeitu 完者笃)', 'Chengzong 成宗', 'Qinming Guangxiao 钦明广孝皇帝', 1294, 1307, 42, 242, 'Yuanshi 元史, annals juan 18-21 (ctext.org)', 'Peace with Japan and Vietnam; the era Dade 大德; succession by military coup becomes Yuan routine from here'),
(244, 'Khayishan', '海山 (Külüg Khan 曲律汗)', 'Wuzong 武宗', 'Renhui Xuanxiao 仁惠宣孝皇帝 (to verify)', 1307, 1311, 42, 243, 'Yuanshi 元史, annals juan 22-24 (ctext.org)', 'Brother-cousin rotation covenant with Ayurbarwada — honoured once, then broken; four-year reign of feasting'),
(245, 'Ayurbarwada', '爱育黎拔力八达 (Buyantu Khan 普颜笃汗)', 'Renzong 仁宗', 'Shengwen Qinxiao 圣文钦孝皇帝', 1311, 1320, 42, 244, 'Yuanshi 元史, annals juan 25-27 (ctext.org)', 'Restored the civil-service examination 1313 after 40 years — with a Mongol quota system; broke the succession covenant in favour of his own son'),
(246, 'Shidebala', '硕德八剌 (Gegeen Khan 格坚汗)', 'Yingzong 英宗', 'Ruisheng Wenxiao 睿圣文孝皇帝 (to verify)', 1320, 1323, 42, 245, 'Yuanshi 元史, annals juan 28 (ctext.org)', 'The New Policies reform; murdered at Nanpo 南坡 with his minister Baiju by the old guard'),
(247, 'Yesün Temür', '也孙铁木儿 (Yesün Temür Khan 额德惠汗)', NULL, 'Taidingdi 泰定帝 (no temple name — his line erased)', 1323, 1328, 42, 246, 'Yuanshi 元史, annals juan 29-30 (ctext.org)', 'Proclaimed emperor on the spot in Mongolia by the Nanpo plotters; posthumously denied a temple name by the victors of 1328'),
(248, 'Ragibagh', '阿速吉八', NULL, 'Tianshundi 天顺帝 (erased)', 1328, 1328, 42, 247,
 'Yuanshi 元史, annals juan 31 / 138 (ctext.org)', 'Child, ~1 month on the throne at Shangdu in the two-capitals war; the Yuanshi annals keep no record of him — known from Tuq Tuqa''s biography. Counted by rule 2, flagged as contested'),
(249, 'Tugh Temür', '图帖睦尔 (Jayaatu Khan 扎牙笃汗)', 'Wenzong 文宗', 'Shengming Yuanxiao 圣明元孝皇帝 (to verify)', 1328, 1332, 42, 248,
 'Yuanshi 元史, annals juan 32-38 (ctext.org)', 'One row, two reigns: 1328-1329, then again 1329-1332 after his brother''s death. He had offered the throne to Khoshila (Mingzong), who died within months at the welcome banquet — the Wenzong poison question of 1329'),
(250, 'Khoshila', '和世㻋 (Kutuktü Khan 忽都笃汗)', 'Mingzong 明宗', 'Yixian Jingxiao 翼献景孝皇帝 (to verify)', 1329, 1329, 42, 249, 'Yuanshi 元史, annals juan 31 / 37 (ctext.org)', 'The brother who came back from the steppe — emperor ~6 months, poisoned at the banquet'),
(251, 'Irinjinbal', '懿璘质班 (Rinchinbal)', 'Ningzong 宁宗', 'Chongsheng Sixiao 冲圣嗣孝皇帝 (to verify)', 1332, 1332, 42, 249, 'Yuanshi 元史, annals juan 37 (ctext.org)', 'Died at 7 after ~2 months'),
(252, 'Toghon Temür', '妥懽帖睦尔 (Ukhaghatu Khan 乌哈笃汗)', 'Huizong 惠宗', 'none (the Ming called him Shundi 顺帝 — "the compliant")', 1333, 1368, 42, 251,
 'Yuanshi 元史, annals juan 38-47 (ctext.org)', 'Last Yuan emperor of China; left Dadu for the steppe 1368 without a battle. The "Shundi" name is the Ming dynasty''s verdict — note the two Huizongs now in this database (Song 宋徽宗 id 211, Yuan 元惠宗 id 252)'),
(253, 'Zhu Yuanzhang', '朱元璋 (Zhu Chongba 朱重八 by birth)', 'Taizu 太祖', 'Gao Huangdi 高皇帝 (full 谥 to verify)', 1368, 1398, 43, NULL,
 'Mingshi 明史, annals juan 1-3 (ctext.org)', 'Beggar-monk to emperor; took Beijing from the Yuan 1368; the Hongwu era 洪武. His "grand pronouncements" 大诰 made law personal; killed tens of thousands in the Hu Weiyong and Lan Yu purges'),
(254, 'Zhu Yunwen', '朱允炆', 'Huizong 惠帝', 'Rang Huangdi 让皇帝 (Southern Ming, to verify)', 1398, 1402, 43, 253,
 'Mingshi 明史, annals juan 4 (ctext.org)', 'Jianwen reign 建文; "cut the vassals" too fast; vanished when Zhu Di took Nanjing 1402 (burned palace, no body — the Ming founding mystery, and the pretext for Zheng He''s voyages). Temple name erased, later restored'),
(255, 'Zhu Di', '朱棣', 'Chengzu 成祖', 'Wendi 文皇帝 (full 谥 to verify)', 1402, 1424, 43, 254,
 'Mingshi 明史, annals juan 5-8 (ctext.org)', 'Usurped in the Jingnan war 靖难; capital to Beijing, Forbidden City built; Zheng He''s fleet to the Indian Ocean; the Yongle dadian encyclopedia'),
(256, 'Zhu Gaochi', '朱高炽', 'Renzong 仁宗', 'Zhao Huangdi 昭皇帝', 1424, 1425, 43, 255, 'Mingshi 明史, annals juan 8 (ctext.org)', 'Ten months of reversal of his father''s harshness'),
(257, 'Zhu Zhanji', '朱瞻基', 'Xuanzong 宣宗', 'Zhang Huangdi 章皇帝', 1425, 1435, 43, 256, 'Mingshi 明史, annals juan 9-10 (ctext.org)', 'Ren-Xuan flourishing; an emperor-painter (dog and bamboo); eunuch school founded — the seed of later eunuch rule'),
(258, 'Zhu Qizhen', '朱祁镇', 'Yingzong 英宗', 'Rui Huangdi 睿皇帝', 1435, 1464, 43, 257,
 'Mingshi 明史, annals juan 10-12 (ctext.org)', 'One row, two reigns: 1435-1449 (Zhengtong) — captured by the Oirats at the Tumu crisis 1449, hostage a year; restored 1457-1464 (Tianshun) after his brother''s death; killed Yu Qian, the defender of Beijing'),
(259, 'Zhu Qiyu', '朱祁钰', 'Daizong 代宗', 'Jing Huangdi 景皇帝', 1449, 1457, 43, 258, 'Mingshi 明史, annals juan 11 (ctext.org)', 'The Jingtai reign that won the defence of Beijing while his brother was captive; buried outside the Ming tombs'),
(260, 'Zhu Jianshen', '朱见深', 'Xianzong 宪宗', 'Chun Huangdi 纯皇帝', 1464, 1487, 43, 258, 'Mingshi 明史, annals juan 13-14 (ctext.org)', 'Succeeded his father Yingzong after the 1457 restoration (predecessor id 258); rehabilitated Yu Qian; Wan Guifei''s secret police (Xichang) and the era Chenghua porcelain'),
(261, 'Zhu Youtang', '朱祐樘', 'Xiaozong 孝宗', 'Jing Huangdi 敬皇帝', 1487, 1505, 43, 260, 'Mingshi 明史, annals juan 15 (ctext.org)', 'The one-woman emperor (Hongzhi); the model virtuous reign by Ming historians'' lights'),
(262, 'Zhu Houzhao', '朱厚照', 'Wuzong 武宗', 'Yi Huangdi 毅皇帝', 1505, 1521, 43, 261, 'Mingshi 明史, annals juan 16 (ctext.org)', 'The playboy war-emperor (self-styled Great General Zhu Shou); died without a son — succession to a cousin'),
(263, 'Zhu Houcong', '朱厚熜', 'Shizong 世宗', 'Su Huangdi 肃皇帝', 1521, 1567, 43, 262, 'Mingshi 明史, annals juan 17-18 (ctext.org)', 'The Great Rites Controversy (大礼议); decades absent from court for Daoist alchemy; Yan Song''s corruption; Jiajing era'),
(264, 'Zhu Zaiji', '朱载坖 (written 朱载垕 in older books)', 'Muzong 穆宗', 'Zhuang Huangdi 庄皇帝', 1567, 1572, 43, 263, 'Mingshi 明史, annals juan 19 (ctext.org)', 'Longqing era; opened the sea trade ban (隆庆开关); even his personal name is uncertain in sources — 坖 vs 垕, noted'),
(265, 'Zhu Yijun', '朱翊钧', 'Shenzong 神宗', 'Xian Huangdi 显皇帝', 1572, 1620, 43, 264, 'Mingshi 明史, annals juan 20-22 (ctext.org)', 'Wanli era — 48 years, ~30 of them refusing to see ministers; the Korean war against Hideyoshi 1592-1598; the Mingshi verdict: "Ming fell in the Wanli reign" (明之亡，实亡于神宗)'),
(266, 'Zhu Changluo', '朱常洛', 'Guangzong 光宗', 'Zhen Huangdi 贞皇帝', 1620, 1620, 43, 265, 'Mingshi 明史, annals juan 21 (ctext.org)', 'One month — and the "three great cases" (三大案) of the late Ming court cluster around his death'),
(267, 'Zhu Youjiao', '朱由校', 'Xizong 熹宗', 'Zhe Huangdi 悊皇帝', 1620, 1627, 43, 266, 'Mingshi 明史, annals juan 22 (ctext.org)', 'The carpenter emperor; power with eunuch Wei Zhongxian and the Donglin persecutions'),
(268, 'Zhu Youjian', '朱由检', 'Sizong 思宗 (Yizong 毅宗 by the Southern Ming)', 'Lie Huangdi 烈皇帝', 1627, 1644, 43, 267,
 'Mingshi 明史, annals juan 23-24 (ctext.org)', 'Hanged himself on Meishan as Li Zicheng entered Beijing, April 1644 — his last edict asked the rebels to spare his subjects; the Chongzhen reign ends the Ming line of China proper'),
(269, 'Nurhaci', '努尔哈赤 (Aisin Gioro Nurgaci 爱新觉罗·努尔哈赤)', 'Taizu 太祖', 'Gao Huangdi 高皇帝 (full 谥 to verify)', 1616, 1626, 44, NULL,
 'Qingshi gao 清史稿, annals juan 1-2', 'Founder of Later Jin 后金 1616 — a khan, not yet a Qing emperor; included from the state''s founding (design rule 3); died of wounds after the defeat at Ningyuan 1626'),
(270, 'Hong Taiji', '皇太极 (Aisin Gioro Hong Taiji 爱新觉罗·皇太极)', 'Taizong 太宗', 'Wendi 文皇帝', 1626, 1643, 44, 269, 'Qingshi gao 清史稿, annals juan 2-3', 'Renamed the state Qing 清 1636 and the clan Aisin Gioro; took Liaodong; died suddenly 1643 — succession by Dorgon''s regency'),
(271, 'Fulin', '福临 (Aisin Gioro Fulin 爱新觉罗·福临)', 'Shizu 世祖', 'Zhang Huangdi 章皇帝 (Shunzhi 顺治)', 1643, 1661, 44, 270,
 'Qingshi gao 清史稿, annals juan 4-6', 'Child emperor under regents Dorgon and Jirgalang; entered Beijing 1644 — Qing rule of China proper begins; later drawn to Chan Buddhism; smallpox at 22'),
(272, 'Xuanye', '玄烨 (Aisin Gioro Xuanye 爱新觉罗·玄烨)', 'Shengzu 圣祖', 'Ren Huangdi 仁皇帝 (Kangxi 康熙)', 1661, 1722, 44, 271,
 'Qingshi gao 清史稿, annals juan 6-8', 'Took power from Oboi 1669; crushed the Revolt of the Three Feudatories 1673-1681, took Taiwan 1683; Treaty of Nerchinsk 1689 — longest reign in Chinese history (61 years)'),
(273, 'Yinzhen', '胤禛 (Aisin Gioro Yinzhen 爱新觉罗·胤禛)', 'Shizong 世宗', 'Xian Huangdi 宪皇帝 (Yongzheng 雍正)', 1722, 1735, 44, 272,
 'Qingshi gao 清史稿, annals juan 9-10', 'The succession letter hidden behind the screen (the "changed 14 to 4" legend is fiction, but the succession was contested); fiscal rigour, the gaitan tax reform, secret palace memorials'),
(274, 'Hongli', '弘历 (Aisin Gioro Hongli 爱新觉罗·弘历)', 'Gaozong 高宗', 'Chun Huangdi 纯皇帝 (Qianlong 乾隆)', 1735, 1796, 44, 273,
 'Qingshi gao 清史稿, annals juan 10-16', 'Six southern tours; the ten campaigns; literary inquisition at its height; abdicated 1796 to avoid out-reigning his grandfather — kept power as retired emperor to 1799; Macartney''s 1793 audience'),
(275, 'Yongyan', '颙琰 (Aisin Gioro Yongyan 爱新觉罗·颙琰)', 'Renzong 仁宗', 'Rui Huangdi 睿皇帝 (Jiaqing 嘉庆)', 1796, 1820, 44, 274, 'Qingshi gao 清史稿, annals juan 16-17', 'Executed Heshen, could not stop the fiscal decline or the White Lotus rising'),
(276, 'Minning', '旻宁 (Aisin Gioro Minning 爱新觉罗·旻宁)', 'Xuanzong 宣宗', 'Cheng Huangdi 成皇帝 (Daoguang 道光)', 1820, 1850, 44, 275,
 'Qingshi gao 清史稿, annals juan 17-19', 'The First Opium War 1839-1842, Treaty of Nanjing 1842 — first of the unequal treaties; famously frugal, terminally outmanoeuvred'),
(277, 'Yizhu', '奕詝 (Aisin Gioro Yizhu 爱新觉罗·奕詝)', 'Wenzong 文宗', 'Xian Huangdi 显皇帝 (Xianfeng 咸丰)', 1850, 1861, 44, 276, 'Qingshi gao 清史稿, annals juan 19-20', 'Taiping Rebellion from 1851; Second Opium War; fled to Chengde 1860, died there — the dowager Cixi''s regency begins (excluded by rule 3, recorded here)'),
(278, 'Zaichun', '载淳 (Aisin Gioro Zaichun 爱新觉罗·载淳)', 'Muzong 穆宗', 'Yi Huangdi 毅皇帝 (Tongzhi 同治)', 1861, 1875, 44, 277, 'Qingshi gao 清史稿, annals juan 21-22', 'Two dowager regents, Cixi and Ci''an; the Tongzhi restoration and the Self-Strengthening Movement; died of smallpox (syphilis in the rumours)'),
(279, 'Zaitian', '载湉 (Aisin Gioro Zaitian 爱新觉罗·载湉)', 'Dezong 德宗', 'Jing Huangdi 景皇帝 (Guangxu 光绪)', 1875, 1908, 44, 278,
 'Qingshi gao 清史稿, annals juan 23-25', 'The Hundred Days'' Reform 1898, house arrest in Zhongnanhai until his death — one day before Cixi''s own (1908); Sino-Japanese War 1894-95 lost under his name'),
(280, 'Puyi', '溥仪 (Aisin Gioro Puyi 爱新觉罗·溥仪)', NULL, 'Xuantong 宣统', 1908, 1912, 44, 279,
 'Qingshi gao 清史稿, annals juan 25; abdication edict of 12 Feb 1912', 'Enthroned at 2, abdicated at 6 (12 February 1912) — the end of two thousand years of imperial rule. His later Manchukuo "reign" 1932-1945 is out of scope, flagged in note');
