-- Batch 8: Southern dynasties — Liu Song 420-479, Southern Qi 479-502,
-- Liang 502-557, Chen 557-589.
-- Sources: Songshu 宋书, Nan Qi shu 南齐书, Liangshu 梁书, Chenshu 陈书 (ctext.org).

INSERT INTO rulers (id, personal_name, personal_name_cn, temple_name, posthumous_name, year_start, year_end, dynasty_id, predecessor_id, source, note) VALUES
(89, 'Liu Yu', '刘裕', 'Gaozu 高祖', 'Wudi 武皇帝', 420, 422, 15, NULL,
 'Songshu 宋书, annals juan 1-3 (ctext.org)', 'Liu Song founder; ended Eastern Jin 420. Watch the romanisation: Liu Yu 刘裕 (this), Liu Yu 刘彧 (id 95), Liu Yu 刘昱 (id 96) — three different emperors, same sound'),
(90, 'Liu Yifu', '刘义符', NULL, 'Shaodi 少帝', 422, 424, 15, 89, 'Songshu 宋书, annals juan 4 (ctext.org)', 'Deposed by ministers Xu Xianzhi and others after frivolous misrule; killed 424'),
(91, 'Liu Yilong', '刘义隆', 'Taizu 太祖', 'Wendi 文皇帝', 424, 453, 15, 90, 'Songshu 宋书, annals juan 5 (ctext.org)', 'Yuanjia flourishing 元嘉之治; beheaded by his own son Liu Shao after 30 years'),
(92, 'Liu Shao', '刘劭', NULL, 'none — executed as a criminal', 453, 453, 15, 91,
 'Songshu 宋书, annals juan 99 二凶传 (ctext.org)', 'Patricide; reigned ~3 months, overthrown by his brother Liu Jun. Officially denied an imperial name; counted here by rule 2, flagged as contested'),
(93, 'Liu Jun', '刘骏', 'Shizu 世祖', 'Xiaowudi 孝武皇帝', 453, 464, 15, 92, 'Songshu 宋书, annals juan 6 (ctext.org)', 'Took the throne by force against Liu Shao; harsh fiscal measures on princes'),
(94, 'Liu Ziye', '刘子业', NULL, 'Qianfei 前废帝', 464, 465, 15, 93, 'Songshu 宋书, annals juan 7 (ctext.org)', 'Sixteen-year-old tyrant; killed by his uncle''s men within a year'),
(95, 'Liu Yu', '刘彧', 'Taizong 太宗', 'Mingdi 明皇帝', 465, 472, 15, 94, 'Songshu 宋书, annals juan 8 (ctext.org)', 'Uncle of Liu Ziye; won the civil war against the princes. Same sound as founder Liu Yu 刘裕 (id 89)'),
(96, 'Liu Yu', '刘昱', NULL, 'Houfei 后废帝', 472, 477, 15, 95,
 'Songshu 宋书, annals juan 9 (ctext.org)', 'A third Liu Yu — same romanisation, different character 昱; teenager killed while out incognito; power passed to Xiao Daocheng'),
(97, 'Liu Zhun', '刘准', NULL, 'Shundi 顺皇帝', 477, 479, 15, 96, 'Songshu 宋书, annals juan 10 (ctext.org)', 'Child; abdicated to Xiao Daocheng 479, killed with all his brothers'),
(98, 'Xiao Daocheng', '萧道成', 'Taizu 太祖', 'Gaodi 高皇帝', 479, 482, 16, 97, 'Nan Qi shu 南齐书, annals juan 1-2 (ctext.org)', 'Received Liu Song''s abdication; "Liu was there to be replaced" — his own telling'),
(99, 'Xiao Ze', '萧赜', 'Shizu 世祖', 'Wudi 武皇帝', 482, 493, 16, 98, 'Nan Qi shu 南齐书, annals juan 3 (ctext.org)', 'Yongming flourishing; his death triggers the princes'' wars'),
(100, 'Xiao Zhaoye', '萧昭业', NULL, 'Deposed, Prince of Yulin 郁林王', 493, 494, 16, 99, 'Nan Qi shu 南齐书, annals juan 4 (ctext.org)', 'Grandson; squandered the treasury; deposed and strangled by Xiao Luan'),
(101, 'Xiao Zhaowen', '萧昭文', NULL, 'Prince of Hailing 海陵恭王', 494, 494, 16, 100, 'Nan Qi shu 南齐书, annals juan 5 (ctext.org)', 'Puppet for ~3 months; killed after Xiao Luan''s usurpation'),
(102, 'Xiao Luan', '萧鸾', 'Gaozong 高宗', 'Mingdi 明皇帝', 494, 498, 16, 101, 'Nan Qi shu 南齐书, annals juan 6 (ctext.org)', 'Usurped from the founder''s grandsons, then exterminated Gao and Wu branches of the imperial clan'),
(103, 'Xiao Baojuan', '萧宝卷', NULL, 'Marquis of Donghun 东昏侯', 498, 501, 16, 102, 'Nan Qi shu 南齐书, annals juan 7 (ctext.org)', 'Killed ministers for fun; "the golden lotuses on the floor" — danced for by Pan Yunu on gilded floor'),
(104, 'Xiao Baorong', '萧宝融', NULL, 'Hedi 和皇帝', 501, 502, 16, 103, 'Nan Qi shu 南齐书, annals juan 8 (ctext.org)', 'Enthroned at Jiangling against Xiao Baojuan; abdicated to Xiao Yan 502, forced to suicide'),
(105, 'Xiao Yan', '萧衍', 'Gaozu 高祖', 'Wudi 武皇帝', 502, 549, 17, 104,
 'Liangshu 梁书, annals juan 1-3 (ctext.org)', 'Liang founder; became a Buddhist "emperor-slave" who "gave himself" to temples three times and was ransomed by the state; starved amid the Hou Jing siege 549, aged 85'),
(106, 'Xiao Gang', '萧纲', 'Taizong 太宗', 'Jianwendi 简文皇帝', 549, 551, 17, 105, 'Liangshu 梁书, annals juan 4 (ctext.org)', 'Puppet of Hou Jing; forced to abdicate, killed 551. Famous as palace-style poet'),
(107, 'Xiao Dong', '萧栋', NULL, 'deposed (Prince of Huaiyin 淮阴王)', 551, 552, 17, 106,
 'Liangshu 梁书, annals juan 5 / Nan shi 南史 (ctext.org)', 'Enthroned by Hou Jing as fig leaf for the usurpation; after Hou Jing''s fall, drowned by Liang generals — with his brothers, "in one day"'),
(108, 'Xiao Yi', '萧绎', 'Shizu 世祖', 'Yuandi 元皇帝', 552, 554, 17, 107, 'Liangshu 梁书, annals juan 5 (ctext.org)', 'Ruled from Jiangling; burned some 140,000 juan of the imperial collection as the city fell 554 ("the way of wen and wu ends this night" 文武之道今夜尽矣, attributed to him), then surrendered to Western Wei'),
(109, 'Xiao Fangzhi', '萧方智', NULL, 'Jingdi 敬皇帝', 555, 557, 17, 108, 'Liangshu 梁书, annals juan 6 (ctext.org)', 'Child; a Western Wei puppet briefly, then Chen Baxian''s; abdicated 557, killed'),
(110, 'Chen Baxian', '陈霸先', 'Gaozu 高祖', 'Wudi 武皇帝', 557, 559, 18, 109, 'Chenshu 陈书, annals juan 1-2 (ctext.org)', 'Liang general of humble origin; last southern dynasty founded'),
(111, 'Chen Qian', '陈蒨', 'Shizu 世祖', 'Wendi 文皇帝', 559, 566, 18, 110, 'Chenshu 陈书, annals juan 3 (ctext.org)', 'Consolidated the state against the Wang Lin coalition'),
(112, 'Chen Bozong', '陈伯宗', NULL, 'Feidi 废帝 (Prince of Linhai 临海王)', 566, 568, 18, 111, 'Chenshu 陈书, annals juan 6 (ctext.org)', 'Child; deposed by his uncle Chen Xu'),
(113, 'Chen Xu', '陈顼', 'Gaozong 高宗', 'Xiaoxuan 孝宣皇帝', 568, 582, 18, 112, 'Chenshu 陈书, annals juan 5 (ctext.org)', 'Failed northern expedition against Northern Zhou 577 — the south lost the Huai line for good'),
(114, 'Chen Shubao', '陈叔宝', NULL, 'Houzhu 后主', 582, 589, 18, 113, 'Chenshu 陈书, annals juan 6-7 (ctext.org)', 'Poet of "Flower in the Rear Courtyard" (玉树后庭花), the loaded "sound of a fallen state"; captured by Sui 589, died in office as a subject');
